/*
  Cohort feasibility study app
  Initial SQL Server setup script

  Purpose:
  1. Create the clinical tables expected by the current SQL builder and SQL Server repository.
  2. Create the application tables needed for login, sessions, OTP flows, saved cohorts, and feasibility audit logging.
  3. Provide a practical starter schema for adopters who want to stand up the project on a fresh database.

  Notes:
  - This is a guide schema for initial setup, not a copy of the upstream hospital warehouse.
  - If your source system uses different table or column names, either adapt this script or update the app mappings.
  - The clinical table names below intentionally match the current generated SQL:
      Patient_Info, Diagnosis, Laboratory, Medication
*/

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* ============================================================================
   Core clinical tables used by the current SQL builder
   ============================================================================ */

IF OBJECT_ID(N'dbo.Patient_Info', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Patient_Info (
    OH_PID VARCHAR(20) NOT NULL,
    BIRTH_DATE DATE NULL,
    SEX VARCHAR(20) NULL,
    SEX_CODE CHAR(1) NULL,
    PATIENT_TYPE_CODE VARCHAR(20) NULL,
    PATIENT_TYPE_NAME VARCHAR(100) NULL,
    RACE_NAME VARCHAR(50) NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_Patient_Info_CREATED_AT DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_Patient_Info_UPDATED_AT DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_Patient_Info PRIMARY KEY CLUSTERED (OH_PID)
  );
END;
GO

IF OBJECT_ID(N'dbo.Diagnosis', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Diagnosis (
    DIAGNOSIS_ID BIGINT IDENTITY(1,1) NOT NULL,
    OH_PID VARCHAR(20) NOT NULL,
    ICD_CODE VARCHAR(20) NOT NULL,
    VISIT_DATE DATE NOT NULL,
    DISEASE_NAME VARCHAR(200) NULL,
    VISIT_OR_ADMIT_NO VARCHAR(30) NULL,
    PATIENT_CATEGORY VARCHAR(10) NULL,
    ICD_VERSION VARCHAR(10) NULL,
    DIAGNOSIS_TYPE CHAR(1) NULL,
    AGE_AT_VISIT SMALLINT NULL,
    DIAGNOSIS_SEQ SMALLINT NULL,
    DIAGNOSIS_GRP VARCHAR(10) NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_Diagnosis_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_Diagnosis PRIMARY KEY CLUSTERED (DIAGNOSIS_ID),
    CONSTRAINT FK_Diagnosis_Patient_Info FOREIGN KEY (OH_PID) REFERENCES dbo.Patient_Info (OH_PID)
  );
END;
GO

IF OBJECT_ID(N'dbo.Laboratory', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Laboratory (
    LAB_RESULT_ID BIGINT IDENTITY(1,1) NOT NULL,
    OH_PID VARCHAR(20) NOT NULL,
    LAB_CODE VARCHAR(30) NOT NULL,
    RESULT_DATE DATE NOT NULL,
    LAB_VALUE DECIMAL(18,4) NULL,
    LAB_NAME VARCHAR(200) NOT NULL,
    LAB_GROUP_CODE VARCHAR(20) NULL,
    LAB_GROUP_NAME VARCHAR(100) NULL,
    AGE_AT_TEST SMALLINT NULL,
    REFERRING_CLINIC VARCHAR(100) NULL,
    PATIENT_CATEGORY VARCHAR(20) NULL,
    LAB_DEPT_CODE VARCHAR(20) NULL,
    LAB_DEPT_NAME VARCHAR(100) NULL,
    LAB_VALUE_TEXT VARCHAR(100) NULL,
    RESULT_UNIT VARCHAR(50) NULL,
    REFERENCE_RANGE VARCHAR(100) NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_Laboratory_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_Laboratory PRIMARY KEY CLUSTERED (LAB_RESULT_ID),
    CONSTRAINT FK_Laboratory_Patient_Info FOREIGN KEY (OH_PID) REFERENCES dbo.Patient_Info (OH_PID)
  );
END;
GO

IF OBJECT_ID(N'dbo.Medication', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Medication (
    MEDICATION_ID BIGINT IDENTITY(1,1) NOT NULL,
    OH_PID VARCHAR(20) NOT NULL,
    DRUG_CODE VARCHAR(30) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    DRUG_NAME VARCHAR(200) NOT NULL,
    VISIT_NO VARCHAR(30) NULL,
    ADMISSION_NO VARCHAR(30) NULL,
    SERVICE_TYPE VARCHAR(10) NULL,
    DRUG_GROUP_CODE VARCHAR(30) NULL,
    DRUG_GROUP_NAME VARCHAR(200) NULL,
    DOSAGE_INSTRUCTION VARCHAR(500) NULL,
    QUANTITY DECIMAL(10,2) NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_Medication_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_Medication PRIMARY KEY CLUSTERED (MEDICATION_ID),
    CONSTRAINT FK_Medication_Patient_Info FOREIGN KEY (OH_PID) REFERENCES dbo.Patient_Info (OH_PID)
  );
END;
GO

/* Helpful indexes for cohort feasibility queries */

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_Diagnosis_OH_PID_ICD_CODE_VISIT_DATE' AND object_id = OBJECT_ID(N'dbo.Diagnosis'))
BEGIN
  CREATE INDEX IX_Diagnosis_OH_PID_ICD_CODE_VISIT_DATE
    ON dbo.Diagnosis (OH_PID, ICD_CODE, VISIT_DATE);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_Laboratory_OH_PID_LAB_CODE_RESULT_DATE' AND object_id = OBJECT_ID(N'dbo.Laboratory'))
BEGIN
  CREATE INDEX IX_Laboratory_OH_PID_LAB_CODE_RESULT_DATE
    ON dbo.Laboratory (OH_PID, LAB_CODE, RESULT_DATE)
    INCLUDE (LAB_VALUE, LAB_NAME, LAB_GROUP_NAME);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_Medication_OH_PID_DRUG_CODE_ORDER_DATE' AND object_id = OBJECT_ID(N'dbo.Medication'))
BEGIN
  CREATE INDEX IX_Medication_OH_PID_DRUG_CODE_ORDER_DATE
    ON dbo.Medication (OH_PID, DRUG_CODE, ORDER_DATE)
    INCLUDE (DRUG_NAME, DRUG_GROUP_NAME);
END;
GO

/* ============================================================================
   Application tables for auth, state, saved cohorts, and audit
   ============================================================================ */

IF OBJECT_ID(N'dbo.App_Users', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.App_Users (
    USER_ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_App_User_USER_ID DEFAULT NEWID(),
    EMAIL NVARCHAR(255) NOT NULL,
    PASSWORD_HASH NVARCHAR(255) NULL,
    NAME NVARCHAR(255) NOT NULL,
    PROVIDER NVARCHAR(50) NOT NULL CONSTRAINT DF_App_User_AUTH_PROVIDER DEFAULT N'credentials',
    ROLE NVARCHAR(50) NOT NULL CONSTRAINT DF_App_User_ROLE DEFAULT N'researcher',
    GOOGLE_SUB NVARCHAR(255) NULL,
    ACTIVE BIT NOT NULL CONSTRAINT DF_App_User_ACTIVE DEFAULT 1,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_App_User_CREATED_AT DEFAULT SYSUTCDATETIME(),
    PASSWORD_UPDATED_AT DATETIME2(0) NULL,
    LAST_LOGIN_AT DATETIME2(0) NULL,
    CONSTRAINT PK_App_Users PRIMARY KEY CLUSTERED (USER_ID),
    CONSTRAINT UQ_App_Users_EMAIL UNIQUE (EMAIL)
  );
END;
GO

IF OBJECT_ID(N'dbo.User_Sessions', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.User_Sessions (
    SESSION_ID NVARCHAR(128) NOT NULL,
    USER_ID UNIQUEIDENTIFIER NOT NULL,
    STARTED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_User_Sessions_STARTED_AT DEFAULT SYSUTCDATETIME(),
    LAST_SEEN_AT DATETIME2(0) NOT NULL CONSTRAINT DF_App_Session_LAST_SEEN_AT DEFAULT SYSUTCDATETIME(),
    PAGE_VIEWS INT NOT NULL CONSTRAINT DF_User_Sessions_PAGE_VIEWS DEFAULT 0,
    RUN_COUNT INT NOT NULL CONSTRAINT DF_User_Sessions_RUN_COUNT DEFAULT 0,
    USER_AGENT NVARCHAR(512) NULL,
    EXPIRES_AT DATETIME2(0) NOT NULL,
    REVOKED_AT DATETIME2(0) NULL,
    IP_ADDRESS NVARCHAR(64) NULL,
    CONSTRAINT PK_User_Sessions PRIMARY KEY CLUSTERED (SESSION_ID),
    CONSTRAINT FK_User_Sessions_App_Users FOREIGN KEY (USER_ID) REFERENCES dbo.App_Users (USER_ID)
  );
END;
GO

IF OBJECT_ID(N'dbo.Pending_Otp', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Pending_Otp (
    OTP_ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Pending_Otp_OTP_ID DEFAULT NEWID(),
    OTP_PURPOSE NVARCHAR(30) NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL,
    USER_ID UNIQUEIDENTIFIER NULL,
    OTP_HASH NVARCHAR(255) NOT NULL,
    ATTEMPTS INT NOT NULL CONSTRAINT DF_Pending_Otp_ATTEMPTS DEFAULT 0,
    EXPIRES_AT DATETIME2(0) NOT NULL,
    CONSUMED_AT DATETIME2(0) NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_Pending_Otp_CREATED_AT DEFAULT SYSUTCDATETIME(),
    PAYLOAD_JSON NVARCHAR(MAX) NULL,
    CONSTRAINT PK_Pending_Otp PRIMARY KEY CLUSTERED (OTP_ID),
    CONSTRAINT FK_Pending_Otp_App_Users FOREIGN KEY (USER_ID) REFERENCES dbo.App_Users (USER_ID)
  );
END;
GO

IF OBJECT_ID(N'dbo.Saved_Cohorts', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Saved_Cohorts (
    COHORT_ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Saved_Cohort_COHORT_ID DEFAULT NEWID(),
    USER_ID UNIQUEIDENTIFIER NOT NULL,
    NAME NVARCHAR(200) NOT NULL,
    CONFIG_JSON NVARCHAR(MAX) NOT NULL,
    QUESTION NVARCHAR(1000) NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_Saved_Cohort_CREATED_AT DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_Saved_Cohort_UPDATED_AT DEFAULT SYSUTCDATETIME(),
    DELETED_AT DATETIME2(0) NULL,
    CONSTRAINT PK_Saved_Cohorts PRIMARY KEY CLUSTERED (COHORT_ID),
    CONSTRAINT FK_Saved_Cohorts_App_Users FOREIGN KEY (USER_ID) REFERENCES dbo.App_Users (USER_ID),
    CONSTRAINT CK_Saved_Cohort_CONFIG_JSON CHECK (ISJSON(CONFIG_JSON) = 1)
  );
END;
GO

IF OBJECT_ID(N'dbo.Audit_Session_Log', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Audit_Session_Log (
    AUDIT_SESSION_ID NVARCHAR(128) NOT NULL,
    USER_ID UNIQUEIDENTIFIER NULL,
    STARTED_AT DATETIME2(0) NOT NULL,
    LAST_SEEN_AT DATETIME2(0) NOT NULL,
    PAGE_VIEWS INT NOT NULL CONSTRAINT DF_Audit_Session_Log_PAGE_VIEWS DEFAULT 0,
    RUN_COUNT INT NOT NULL CONSTRAINT DF_Audit_Session_Log_RUN_COUNT DEFAULT 0,
    USER_AGENT NVARCHAR(512) NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_Audit_Session_Log_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_Audit_Session_Log PRIMARY KEY CLUSTERED (AUDIT_SESSION_ID),
    CONSTRAINT FK_Audit_Session_Log_App_Users FOREIGN KEY (USER_ID) REFERENCES dbo.App_Users (USER_ID)
  );
END;
GO

IF OBJECT_ID(N'dbo.Feasibility_Run_Logs', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Feasibility_Run_Logs (
    RUN_ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Feasibility_Run_Log_RUN_ID DEFAULT NEWID(),
    SESSION_ID NVARCHAR(128) NULL,
    USER_ID UNIQUEIDENTIFIER NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_Feasibility_Run_Log_CREATED_AT DEFAULT SYSUTCDATETIME(),
    QUESTION NVARCHAR(1000) NULL,
    INDEX_ELIGIBLE_COUNT INT NOT NULL CONSTRAINT DF_Feasibility_Run_Log_INDEX_ELIGIBLE_COUNT DEFAULT 0,
    FINAL_COUNT INT NOT NULL CONSTRAINT DF_Feasibility_Run_Log_FINAL_COUNT DEFAULT 0,
    EXCLUDED_COUNT INT NOT NULL CONSTRAINT DF_Feasibility_Run_Log_EXCLUDED_COUNT DEFAULT 0,
    ATTRITION NVARCHAR(MAX) NULL,
    SELECTED_CONCEPTS NVARCHAR(MAX) NULL,
    CONFIG NVARCHAR(MAX) NOT NULL,
    [SQL] NVARCHAR(MAX) NULL,
    DATA_SOURCE NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_Feasibility_Run_Logs PRIMARY KEY CLUSTERED (RUN_ID),
    CONSTRAINT FK_Feasibility_Run_Logs_User_Sessions FOREIGN KEY (SESSION_ID) REFERENCES dbo.User_Sessions (SESSION_ID),
    CONSTRAINT FK_Feasibility_Run_Logs_App_Users FOREIGN KEY (USER_ID) REFERENCES dbo.App_Users (USER_ID),
    CONSTRAINT CK_Feasibility_Run_Log_ATTRITION CHECK (ATTRITION IS NULL OR ISJSON(ATTRITION) = 1),
    CONSTRAINT CK_Feasibility_Run_Log_SELECTED_CONCEPTS CHECK (SELECTED_CONCEPTS IS NULL OR ISJSON(SELECTED_CONCEPTS) = 1),
    CONSTRAINT CK_Feasibility_Run_Log_CONFIG CHECK (ISJSON(CONFIG) = 1)
  );
END;
GO

IF OBJECT_ID(N'dbo.Auth_Event_Log', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Auth_Event_Log (
    AUTH_EVENT_ID BIGINT IDENTITY(1,1) NOT NULL,
    USER_ID UNIQUEIDENTIFIER NULL,
    EMAIL NVARCHAR(255) NULL,
    EVENT_TYPE NVARCHAR(50) NOT NULL,
    EVENT_STATUS NVARCHAR(20) NOT NULL,
    EVENT_DETAIL NVARCHAR(1000) NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_Auth_Event_Log_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_Auth_Event_Log PRIMARY KEY CLUSTERED (AUTH_EVENT_ID),
    CONSTRAINT FK_Auth_Event_Log_App_Users FOREIGN KEY (USER_ID) REFERENCES dbo.App_Users (USER_ID)
  );
END;
GO

/* Helpful app indexes */

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_User_Sessions_USER_ID_EXPIRES_AT' AND object_id = OBJECT_ID(N'dbo.User_Sessions'))
BEGIN
  CREATE INDEX IX_User_Sessions_USER_ID_EXPIRES_AT
    ON dbo.User_Sessions (USER_ID, EXPIRES_AT);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_Pending_Otp_EMAIL_PURPOSE_EXPIRES_AT' AND object_id = OBJECT_ID(N'dbo.Pending_Otp'))
BEGIN
  CREATE INDEX IX_Pending_Otp_EMAIL_PURPOSE_EXPIRES_AT
    ON dbo.Pending_Otp (EMAIL, OTP_PURPOSE, EXPIRES_AT);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_Saved_Cohorts_USER_ID_UPDATED_AT' AND object_id = OBJECT_ID(N'dbo.Saved_Cohorts'))
BEGIN
  CREATE INDEX IX_Saved_Cohorts_USER_ID_UPDATED_AT
    ON dbo.Saved_Cohorts (USER_ID, UPDATED_AT DESC);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_Feasibility_Run_Logs_CREATED_AT' AND object_id = OBJECT_ID(N'dbo.Feasibility_Run_Logs'))
BEGIN
  CREATE INDEX IX_Feasibility_Run_Logs_CREATED_AT
    ON dbo.Feasibility_Run_Logs (CREATED_AT DESC);
END;
GO

/*
  Minimal seed guidance
  - Insert users into dbo.App_User for credential login.
  - Load patient/event rows into the four core clinical tables for feasibility counts.
  - Persist saved cohorts and audit data in the application tables once the backend moves off JSON/localStorage.
*/
