# Generated by Django 5.2.17 on 2026-09-17 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditSession",
            fields=[
                ("id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("run_count", models.PositiveIntegerField(default=0)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("event_type", models.CharField(max_length=50)),
                ("event_status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeasibilityRun",
            fields=[
                ("id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("session_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField()),
                ("question", models.TextField(blank=True)),
                ("index_eligible_count", models.PositiveIntegerField(default=0)),
                ("final_count", models.PositiveIntegerField(default=0)),
                ("excluded_count", models.PositiveIntegerField(default=0)),
                ("attrition", models.JSONField(default=list)),
                ("selected_concepts", models.JSONField(default=dict)),
                ("config", models.JSONField(default=dict)),
                ("sql", models.TextField(blank=True)),
                ("data_source", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedCohort",
            fields=[
                ("id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("config", models.JSONField(default=dict)),
                ("saved_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PendingOtp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("purpose", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("otp_hash", models.CharField(max_length=255)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("purpose", "email"), name="unique_otp_purpose_email"
                    )
                ],
            },
        ),
    ]
