# Generated by Django 5.2.17 on 2026-09-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(default="researcher", max_length=50)),
                ("provider", models.CharField(default="credentials", max_length=50)),
                (
                    "google_sub",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("password_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "app_users",
            },
        ),
    ]
